# Generated by Django 4.2.5 on 2024-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_rename_created_at_referralclick_clicked_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='referral_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
