# Generated by Django 4.2.5 on 2024-08-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_alter_referrallink_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralclick',
            name='ip_address',
            field=models.GenericIPAddressField(default='0.0.0.0'),
        ),
    ]
