# Generated by Django 4.2.5 on 2024-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0004_alter_referralclick_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralclick',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
